# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUFCcyKElFRG2_tsfiHpzJOrVqXRXBor
"""

################# Dictionary that contains key:value pair in form "number in words":"number in int" i.e. ("ninety one":91) etc############
words_to_number_dict = {"one":1,"two":2,"three":3,"four":4,"five":5,"six":6, "seven":7,
                        "eight":8,"nine":9,"ten":10,"eleven":11,"twelve":12,
                        "thirteen":13,"forteen":14,"fifteen":15,"sixteen":16,
                        "seventeen":17,"eighteen":18,"nineteen":19,"twenty":20,
                        "twenty one":21,"twenty two":22,"twenty three":23,"twenty four":24,
                        "twenty five": 25,"twenty six":26, "twenty seven":27, 
                        "twenty eight":28,"twenty nine":29, "thirty":30, "thirty one":31,
                        "thirty two":32,"thirty three":33,"thirty four":34,"thirty five":35,
                        "thirty six":36, "thirty seven":37, "thirty eight":38,"thirty nine":39,
                        "forty": 40, "forty one":41,"forty two":42,"forty three":43,
                        "forty four":44,"forty five":45,"forty six":46, "forty seven":47,
                        "forty eight":48,"forty nine":49, "fifty":50, "fifty one":51,"fifty two":52,
                        "fifty three":53,"fifty four":54,"fifty five":55,"fifty six":56, "fifty seven":57,
                        "fifty eight":58,"fifty nine":59, "sixty":60, "sixty one":61,
                        "sixty two":62,"sixty three":63,"sixty four":64,"sixty five":65,
                        "sixty six":66, "sixty seven":67,"sixty eight":68,"sixty nine":69, "seventy":70,
                        "seventy one":71,"seventy two":72,"seventy three":73,
                        "seventy four":74,"seventy five":75,"seventy six":76, "seventy seven":77,
                        "seventy eight":78,"seventy nine":79, "eighty":80, "eighty one":81,
                        "eighty two":82,"eighty three":83,"eighty four":84,
                        "eighty five":85,"eighty six":86, "eighty seven":87,"eighty eight":88,
                        "eighty nine":89, "ninety":90 , "ninety one":91,"ninety two":92,
                        "ninety three":93,"ninety four":94,"ninety five":95,"ninety six":96, "ninety seven":97,
                        "ninety eight":98,"ninety nine":99, "hundred":100,"fourty": 40, "fourty one":41,"fourty two":42,"fourty three":43,
                        "fourty four":44,"fourty five":45,"fourty six":46, "fourty seven":47,
                        "fourty eight":48,"fourty nine":49,"tweleve":12}

def number_in_words_to_numbers(words):
  return words_to_number_dict[words]
number_in_words_to_numbers("seventy one")

"""#### Task 1: and task 2:  and task 3"""

class File:#######Task1
  def __init__(self):
    self.path = input("Enter file Path:") # asks for file path when an instance is created and then store it in self.path
  def sum(self):#######Task2
    sum_ =0
    with open(self.path) as f:####opens file present on self.path
      file = f.read()
    words = file.split('\n')###### list of numbers in words
    for i in words:
        if i.strip() in words_to_number_dict:
            sum_ = sum_ + words_to_number_dict[i.strip()]
    return sum_
  def count(self,number):####### task 3
    count_ =0
    with open(self.path) as f:
      file = f.read()
    words = file.split('\n')
    for i in words:
      if i.strip() in words_to_number_dict:
        count_ = count_ + str(words_to_number_dict[i.strip()]).strip().count(str(number))
    return count_

"""testing
1.txt has 
eleven
twelve
ninety
one
"""

f = File()
f.sum()

f.count(1)

"""Task 4 """

import thread
thread.start_new_thread(,"Thread:1")
thread.start_new_thread(,"Thread:2")
thread.start_new_thread(,"Thread:3")
thread.start_new_thread(,"Thread:4")
thread.start_new_thread(,"Thread:5")
thread.start_new_thread(,"Thread:6")
thread.start_new_thread(,"Thread:7")
thread.start_new_thread(,"Thread:8")
thread.start_new_thread(,"Thread:9")
thread.start_new_thread(,"Thread:10")